Final group capstone - Book an Appointment
JoffreyNK/final-capstone pull request #37
Opened 2022-11-11 19:43 UTC by JoffreyNK

### Final group capstone - Book an Appointment

- The user logs in to the website, only by typing the username  and password (a properly authenticated login is a requirement)
- In the navigation panel, the user can see links to:
  -   List vehicles
  -   "Reserve" form.
  -   "My reservations".
  -   Add vehicle ( The link is visible by admin users only)
  -   delete vehicles( The link is visible by admin users only)
  
- On the main page, the user can see a list of vehicles after logging in
- When the user selects a specific vehicle, they can see the vehicle details page 
- In the vehicle details page, the user can click the "Reserve" button 
- When the user clicks the "Add a vehicle" link in the navigation panel they can see a form for adding a new vehicle.
- The app is responsive and created in both mobile and desktop versions.
- When the user clicks the "Delete vehicle" link in the navigation panel they can see a list of all vehicles with title and the "Delete" button
- To reserve an appointment, the user has to select a date and city (username and selected item are auto-filled).
- When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about vehicle name, date, and city).

[the frontend link is here:](https://github.com/[JoffreyNK/final-capstone](https://github.com/JoffreyNK/final-capstone))

our group, they are  remaining  two  at the beginning we were four people it affected us.
Sorry for delay

2022-11-11 19:47 UTC, JoffreyNK commented
We failed t deploy our project that's why it  has deployment errors

2022-11-11 21:23 UTC, Meltrust requested changes
Hi @desorgui,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  API is working well✔️ 
-  Good readme ✔️ 
-  Nice use of Active Storage ✔️ 





#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2022-11-11 21:23 UTC, Meltrust commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ]  On your pull request description, the link to the frontend project does not work:

![image](https://user-images.githubusercontent.com/57421823/201429672-af829e89-733e-4280-8c02-b0a49183873b.png)

Kindly update the link, so it works and your frontend can be accessed and properly reviewed. 👍

2022-11-11 21:23 UTC, Meltrust commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ]  On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project.

## Tips and extra help

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

That way, your app will be well documented 💪

2022-11-11 21:23 UTC, Meltrust commented on README.md
> +    2. xdg-open http://localhost:3000/api/v1
- [ ] Your instructions point in the end to a path that has no route:

![image](https://user-images.githubusercontent.com/57421823/201430267-ce9553ed-61c1-4154-a62d-6e761907dc37.png)

Kindly remove that direction, or add a route to it.   That way, your users won't be lured to an error page. 👍

2022-11-11 21:23 UTC, Meltrust commented on README.md
> +### Usage
- [ ] Your tests are all passing.  On your readme, kindly add a "tests" section, with instructions about how to run your tests.

2022-11-11 21:23 UTC, Meltrust commented on README.md
> +# Car Booking APi
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2022-11-11 21:23 UTC, Meltrust commented on config/routes.rb
> +  end
- [ ] Nice routes and nice use of the `#resources` method.  However, you are generating more routes than needed.  

## Explanation

By using the `only:` keyword parameter, you can generate only the routes that you are using.

[Look](https://launchschool.com/books/demystifying_rails/read/routes_and_resources):

![image](https://user-images.githubusercontent.com/57421823/201431229-f7861d5e-3462-4897-b6fa-1242581bf06f.png)

## Example

For the vehicles controller, I can see that you are only using index, create, show, and destroy (no edit or update).

So:

```ruby
resources :vehicles, only: [:index, :create, :show, :destroy]
```

You can do the same process with the `:users` and `:reservations` routes 👍 

That way, your routes will be more consistent, and only the ones needed will be generated💪

2022-11-12 17:26 UTC, Meltrust approved these changes
_note: Since I couldn't find an open PR from dev to main in the frontend repo, this summary applies to both apps_

#### Hi @JoffreyNK,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

### To highlight

- The app works well✔️
- Nice use of jwt ✔️ 
- Readme has been corrected ✔️ 
- Links have been corrected ✔️ 
- Beautiful frontend  ✔️ 
- Test folder has been removed ✔️ 
- Routes have been condensed  ✔️ 
- Nice code organization ✔️ 



Cheers and Happy coding!👏👏👏


------

2022-11-12 17:37 UTC, merged